version: "3.7"
volumes:
  k6_store:
networks:
  test_net:
  grafana:
services:
  haskell_http_server:
    image: hs-test-server
    ports:
      - "8080:8080"
    networks:
      - test_net
    profiles:
      - http-hs
    cpu_count: ${CORES}
  rust_http_server:
    image: rs-test-server-http
    ports:
      - "8080:8080"
    networks:
      - test_net
    profiles:
      - http-rs
    cpu_count: ${CORES}
  rust_grpc_server:
    image: rs-test-server-grpc
    ports:
      - "8080:8080"
    networks:
      - test_net
    profiles:
      - grpc
    cpu_count: ${CORES}
  influxdb:
    image: influxdb:1.8
    networks:
      - test_net
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./config/dashboards:/var/lib/grafana/dashboards
      - ./config/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./config/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
  k6:
    image: grafana/k6:latest
    command: run /scripts/${SCRIPT}
    # command: run /scripts/http-hs.js
    # command: run /scripts/grpc.js
    profiles:
      - test
    networks:
      - test_net
      - grafana
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts
